SELECT COUNT(DISTINCT dept_id) 
FROM  STUDENT

SELECT COUNT(*)
FROM STUDENT s , DEPARTMENT d 
WHERE s.DEPT_ID =d.DEPT_ID AND d.DEPT_NAME ='컴퓨터공학과'

SELECT COUNT(*) 
FROM EMP
WHERE job='SALESMAN' AND SAL>='1500'

SELECT SUM(2012-YEAR_EMP)
FROM PROFESSOR

SELECT SUM(SAL) 
FROM EMP
WHERE JOB='SALESMAN'

SELECT AVG(2012-YEAR_EMP)
FROM PROFESSOR

SELECT AVG(SAL)
FROM EMP
WHERE JOB='CLERK'

SELECT AVG(SAL)
FROM EMP
WHERE JOB='SALESMAN'

SELECT AVG(SAL)
FROM EMP
WHERE JOB='MANAGER'

SELECT AVG(SAL)
FROM EMP
WHERE JOB='ANALYST'

SELECT AVG(SAL)
FROM EMP
WHERE JOB='PRESIDENT'

SELECT MAX(SAL),AVG(SAL),MIN(SAL)  
FROM EMP e ,DEPT d 
WHERE E.DEPTNO =D.DEPTNO AND DNAME='ACCOUNTING'

SELECT DEPT_ID,COUNT(*) 
FROM STUDENT
GROUP BY DEPT_ID

SELECT DEPT_NAME,COUNT(*)
FROM STUDENT s ,DEPARTMENT d 
WHERE S.DEPT_ID =D.DEPT_ID 
GROUP BY DEPT_NAME

SELECT DNAME,COUNT(*),AVG(SAL),MAX(SAL),MIN(SAL)
FROM EMP E,DEPT d 
WHERE E.DEPTNO =d.DEPTNO 
GROUP BY DNAME
HAVING count(*)>=5

SELECT dept_name,COUNT(*),avg(2012-year_emp) 평균,max(2012-year_emp) 
FROM PROFESSOR p ,DEPARTMENT d 
WHERE p.DEPT_ID =d.DEPT_ID 
GROUP BY dept_name
HAVING avg(2012-YEAR_EMP)>=10

SELECT *
FROM EMP
WHERE comm <> 1400

SELECT stu_id
FROM TAKES
WHERE grade <> 'A+'

SELECT TITLE
FROM COURSE
WHERE COURSE_ID IN(SELECT DISTINCT COURSE_ID
FROM CLASS
WHERE CLASSROOM='301호')

SELECT DISTINCT TITLE
FROM COURSE c1, CLASS c2
WHERE C1.COURSE_ID =C2.COURSE_ID AND CLASSROOM='301호'

SELECT TITLE
FROM COURSE
WHERE COURSE_ID NOT IN(SELECT DISTINCT COURSE_ID
FROM CLASS
WHERE YEAR=2012 AND SEMESTER=2)

CREATE OR REPLACE VIEW V_TAKES AS
SELECT STU_ID,CLASS_ID
FROM TAKES

SELECT * FROM V_TAKES